name: 'Lighthouse Maven Build'
description: 'Build Java projects with Maven for use with Lighthouse'
inputs:
  nexus-username:
    description: 'Nexus user name'
    required: true
  nexus-password:
    description: 'Nexus password'
    required: true
  command:
    description: 'Type of build to create, e.g. non-release'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/build.sh ${{ inputs.command }} \
          --nexus-username ${{ inputs.nexus-username }} \
          --nexus-password ${{ inputs.nexus-password }}
      shell: bash
